# Do not edit! Generated automatically by mockfacebook.
# http://code.google.com/p/mockfacebook/
# 2011-10-28 15:41:32.931426

{'tables': {'album': (Column(name='aid', fb_type='string', sqlite_type='TEXT', indexable=True),
                      Column(name='object_id', fb_type='int', sqlite_type='INTEGER', indexable=True),
                      Column(name='owner', fb_type='int', sqlite_type='INTEGER', indexable=True),
                      Column(name='cover_pid', fb_type='string', sqlite_type='TEXT', indexable=False),
                      Column(name='cover_object_id', fb_type='string', sqlite_type='TEXT', indexable=False),
                      Column(name='name', fb_type='string', sqlite_type='TEXT', indexable=False),
                      Column(name='created', fb_type='int', sqlite_type='INTEGER', indexable=False),
                      Column(name='modified', fb_type='int', sqlite_type='INTEGER', indexable=False),
                      Column(name='description', fb_type='string', sqlite_type='TEXT', indexable=False),
                      Column(name='location', fb_type='string', sqlite_type='TEXT', indexable=False),
                      Column(name='size', fb_type='int', sqlite_type='INTEGER', indexable=False),
                      Column(name='link', fb_type='string', sqlite_type='TEXT', indexable=False),
                      Column(name='visible', fb_type='string', sqlite_type='TEXT', indexable=False),
                      Column(name='modified_major', fb_type='int', sqlite_type='INTEGER', indexable=False),
                      Column(name='edit_link', fb_type='string', sqlite_type='TEXT', indexable=False),
                      Column(name='type', fb_type='string', sqlite_type='TEXT', indexable=False),
                      Column(name='can_upload', fb_type='bool', sqlite_type='INTEGER', indexable=False),
                      Column(name='photo_count', fb_type='int', sqlite_type='INTEGER', indexable=False),
                      Column(name='video_count', fb_type='int', sqlite_type='INTEGER', indexable=False)),
            'application': (Column(name='app_id', fb_type='string', sqlite_type='TEXT', indexable=True),
                            Column(name='api_key', fb_type='string', sqlite_type='TEXT', indexable=True),
                            Column(name='canvas_name', fb_type='string', sqlite_type='TEXT', indexable=True),
                            Column(name='display_name', fb_type='string', sqlite_type='TEXT', indexable=False),
                            Column(name='icon_url', fb_type='string', sqlite_type='TEXT', indexable=False),
                            Column(name='logo_url', fb_type='string', sqlite_type='TEXT', indexable=False),
                            Column(name='company_name', fb_type='string', sqlite_type='TEXT', indexable=False),
                            Column(name='developers', fb_type='object', sqlite_type='', indexable=False),
                            Column(name='description', fb_type='string', sqlite_type='TEXT', indexable=False),
                            Column(name='daily_active_users', fb_type='string', sqlite_type='TEXT', indexable=False),
                            Column(name='weekly_active_users', fb_type='string', sqlite_type='TEXT', indexable=False),
                            Column(name='monthly_active_users', fb_type='string', sqlite_type='TEXT', indexable=False),
                            Column(name='category', fb_type='string', sqlite_type='TEXT', indexable=False),
                            Column(name='subcategory', fb_type='string', sqlite_type='TEXT', indexable=False),
                            Column(name='is_facebook_app', fb_type='bool', sqlite_type='INTEGER', indexable=False),
                            Column(name='restriction_info', fb_type='object', sqlite_type='', indexable=False)),
            'apprequest': (Column(name='request_id', fb_type='string', sqlite_type='TEXT', indexable=True),
                           Column(name='app_id', fb_type='string', sqlite_type='TEXT', indexable=True),
                           Column(name='recipient_uid', fb_type='string', sqlite_type='TEXT', indexable=True),
                           Column(name='sender_uid', fb_type='string', sqlite_type='TEXT', indexable=False),
                           Column(name='message', fb_type='string', sqlite_type='TEXT', indexable=False),
                           Column(name='data', fb_type='string', sqlite_type='TEXT', indexable=False),
                           Column(name='created_time', fb_type='int', sqlite_type='INTEGER', indexable=False)),
            'checkin': (Column(name='checkin_id', fb_type='int', sqlite_type='INTEGER', indexable=True),
                        Column(name='author_uid', fb_type='int', sqlite_type='INTEGER', indexable=True),
                        Column(name='page_id', fb_type='int', sqlite_type='INTEGER', indexable=True),
                        Column(name='app_id', fb_type='int', sqlite_type='INTEGER', indexable=False),
                        Column(name='post_id', fb_type='int', sqlite_type='INTEGER', indexable=False),
                        Column(name='coords', fb_type='array', sqlite_type='', indexable=False),
                        Column(name='timestamp', fb_type='int', sqlite_type='INTEGER', indexable=False),
                        Column(name='tagged_uids', fb_type='array', sqlite_type='', indexable=False),
                        Column(name='message', fb_type='string', sqlite_type='TEXT', indexable=False)),
            'comment': (Column(name='xid', fb_type='string', sqlite_type='TEXT', indexable=True),
                        Column(name='object_id', fb_type='int', sqlite_type='INTEGER', indexable=True),
                        Column(name='post_id', fb_type='string', sqlite_type='TEXT', indexable=True),
                        Column(name='fromid', fb_type='int', sqlite_type='INTEGER', indexable=False),
                        Column(name='time', fb_type='int', sqlite_type='INTEGER', indexable=False),
                        Column(name='text', fb_type='string', sqlite_type='TEXT', indexable=False),
                        Column(name='id', fb_type='string', sqlite_type='TEXT', indexable=False),
                        Column(name='username', fb_type='string', sqlite_type='TEXT', indexable=False),
                        Column(name='reply_xid', fb_type='string', sqlite_type='TEXT', indexable=False),
                        Column(name='post_fbid', fb_type='string', sqlite_type='TEXT', indexable=False),
                        Column(name='app_id', fb_type='int', sqlite_type='INTEGER', indexable=False),
                        Column(name='likes', fb_type='int', sqlite_type='INTEGER', indexable=False),
                        Column(name='comments', fb_type='array', sqlite_type='', indexable=False),
                        Column(name='user_likes', fb_type='bool', sqlite_type='INTEGER', indexable=False),
                        Column(name='is_private', fb_type='bool', sqlite_type='INTEGER', indexable=False)),
            'comments_info': (Column(name='app_id', fb_type='string', sqlite_type='TEXT', indexable=True),
                              Column(name='xid', fb_type='string', sqlite_type='TEXT', indexable=False),
                              Column(name='count', fb_type='int', sqlite_type='INTEGER', indexable=False),
                              Column(name='updated_time', fb_type='int', sqlite_type='INTEGER', indexable=False)),
            'connection': (Column(name='source_id', fb_type='int', sqlite_type='INTEGER', indexable=True),
                           Column(name='target_id', fb_type='int', sqlite_type='INTEGER', indexable=True),
                           Column(name='target_type', fb_type='string', sqlite_type='TEXT', indexable=False),
                           Column(name='is_following', fb_type='bool', sqlite_type='INTEGER', indexable=False)),
            'cookies': (Column(name='uid', fb_type='string', sqlite_type='TEXT', indexable=True),
                        Column(name='name', fb_type='string', sqlite_type='TEXT', indexable=False),
                        Column(name='value', fb_type='string', sqlite_type='TEXT', indexable=False),
                        Column(name='expires', fb_type='int', sqlite_type='INTEGER', indexable=False),
                        Column(name='path', fb_type='string', sqlite_type='TEXT', indexable=False)),
            'developer': (Column(name='developer_id', fb_type='string', sqlite_type='TEXT', indexable=True),
                          Column(name='application_id', fb_type='string', sqlite_type='TEXT', indexable=False)),
            'domain': (Column(name='domain_id', fb_type='int', sqlite_type='INTEGER', indexable=True),
                       Column(name='domain_name', fb_type='string', sqlite_type='TEXT', indexable=True)),
            'domain_admin': (Column(name='owner_id', fb_type='string', sqlite_type='TEXT', indexable=True),
                             Column(name='domain_id', fb_type='string', sqlite_type='TEXT', indexable=True)),
            'event': (Column(name='eid', fb_type='int', sqlite_type='INTEGER', indexable=True),
                      Column(name='name', fb_type='string', sqlite_type='TEXT', indexable=False),
                      Column(name='tagline', fb_type='string', sqlite_type='TEXT', indexable=False),
                      Column(name='nid', fb_type='int', sqlite_type='INTEGER', indexable=False),
                      Column(name='pic_small', fb_type='string', sqlite_type='TEXT', indexable=False),
                      Column(name='pic_big', fb_type='string', sqlite_type='TEXT', indexable=False),
                      Column(name='pic_square', fb_type='string', sqlite_type='TEXT', indexable=False),
                      Column(name='pic', fb_type='string', sqlite_type='TEXT', indexable=False),
                      Column(name='host', fb_type='string', sqlite_type='TEXT', indexable=False),
                      Column(name='description', fb_type='string', sqlite_type='TEXT', indexable=False),
                      Column(name='event_type', fb_type='string', sqlite_type='TEXT', indexable=False),
                      Column(name='event_subtype', fb_type='string', sqlite_type='TEXT', indexable=False),
                      Column(name='start_time', fb_type='int', sqlite_type='INTEGER', indexable=False),
                      Column(name='end_time', fb_type='int', sqlite_type='INTEGER', indexable=False),
                      Column(name='creator', fb_type='int', sqlite_type='INTEGER', indexable=False),
                      Column(name='update_time', fb_type='int', sqlite_type='INTEGER', indexable=False),
                      Column(name='location', fb_type='string', sqlite_type='TEXT', indexable=False),
                      Column(name='venue', fb_type='object', sqlite_type='', indexable=False),
                      Column(name='privacy', fb_type='string', sqlite_type='TEXT', indexable=False),
                      Column(name='hide_guest_list', fb_type='bool', sqlite_type='INTEGER', indexable=False),
                      Column(name='can_invite_friends', fb_type='bool', sqlite_type='INTEGER', indexable=False)),
            'event_member': (Column(name='uid', fb_type='string', sqlite_type='TEXT', indexable=True),
                             Column(name='eid', fb_type='string', sqlite_type='TEXT', indexable=True),
                             Column(name='rsvp_status', fb_type='string', sqlite_type='TEXT', indexable=False),
                             Column(name='start_time', fb_type='int', sqlite_type='INTEGER', indexable=False)),
            'family': (Column(name='profile_id', fb_type='string', sqlite_type='TEXT', indexable=True),
                       Column(name='uid', fb_type='string', sqlite_type='TEXT', indexable=False),
                       Column(name='name', fb_type='string', sqlite_type='TEXT', indexable=False),
                       Column(name='birthday', fb_type='string', sqlite_type='TEXT', indexable=False),
                       Column(name='relationship', fb_type='string', sqlite_type='TEXT', indexable=False)),
            'friend': (Column(name='uid1', fb_type='string', sqlite_type='TEXT', indexable=True),
                       Column(name='uid2', fb_type='string', sqlite_type='TEXT', indexable=True)),
            'friend_request': (Column(name='uid_to', fb_type='string', sqlite_type='TEXT', indexable=True),
                               Column(name='uid_from', fb_type='string', sqlite_type='TEXT', indexable=True),
                               Column(name='time', fb_type='int', sqlite_type='INTEGER', indexable=False),
                               Column(name='message', fb_type='string', sqlite_type='TEXT', indexable=False),
                               Column(name='unread', fb_type='bool', sqlite_type='INTEGER', indexable=False)),
            'friendlist': (Column(name='owner', fb_type='int', sqlite_type='INTEGER', indexable=True),
                           Column(name='flid', fb_type='string', sqlite_type='TEXT', indexable=True),
                           Column(name='name', fb_type='string', sqlite_type='TEXT', indexable=False)),
            'friendlist_member': (Column(name='flid', fb_type='string', sqlite_type='TEXT', indexable=True),
                                  Column(name='uid', fb_type='int', sqlite_type='INTEGER', indexable=True)),
            'group': (Column(name='gid', fb_type='int', sqlite_type='INTEGER', indexable=True),
                      Column(name='name', fb_type='string', sqlite_type='TEXT', indexable=False),
                      Column(name='nid', fb_type='int', sqlite_type='INTEGER', indexable=False),
                      Column(name='pic_small', fb_type='string', sqlite_type='TEXT', indexable=False),
                      Column(name='pic_big', fb_type='string', sqlite_type='TEXT', indexable=False),
                      Column(name='pic', fb_type='string', sqlite_type='TEXT', indexable=False),
                      Column(name='description', fb_type='string', sqlite_type='TEXT', indexable=False),
                      Column(name='group_type', fb_type='string', sqlite_type='TEXT', indexable=False),
                      Column(name='group_subtype', fb_type='string', sqlite_type='TEXT', indexable=False),
                      Column(name='recent_news', fb_type='string', sqlite_type='TEXT', indexable=False),
                      Column(name='creator', fb_type='int', sqlite_type='INTEGER', indexable=False),
                      Column(name='update_time', fb_type='int', sqlite_type='INTEGER', indexable=False),
                      Column(name='office', fb_type='string', sqlite_type='TEXT', indexable=False),
                      Column(name='website', fb_type='string', sqlite_type='TEXT', indexable=False),
                      Column(name='venue', fb_type='object', sqlite_type='', indexable=False),
                      Column(name='privacy', fb_type='string', sqlite_type='TEXT', indexable=False),
                      Column(name='icon', fb_type='string', sqlite_type='TEXT', indexable=False),
                      Column(name='icon34', fb_type='string', sqlite_type='TEXT', indexable=False),
                      Column(name='icon68', fb_type='string', sqlite_type='TEXT', indexable=False),
                      Column(name='email', fb_type='string', sqlite_type='TEXT', indexable=False),
                      Column(name='version', fb_type='int', sqlite_type='INTEGER', indexable=False)),
            'group_member': (Column(name='uid', fb_type='string', sqlite_type='TEXT', indexable=True),
                             Column(name='gid', fb_type='string', sqlite_type='TEXT', indexable=True),
                             Column(name='administrator', fb_type='bool', sqlite_type='INTEGER', indexable=False),
                             Column(name='positions', fb_type='object', sqlite_type='', indexable=False),
                             Column(name='unread', fb_type='int', sqlite_type='INTEGER', indexable=False),
                             Column(name='bookmark_order', fb_type='int', sqlite_type='INTEGER', indexable=False)),
            'like': (Column(name='object_id', fb_type='int', sqlite_type='INTEGER', indexable=True),
                     Column(name='post_id', fb_type='string', sqlite_type='TEXT', indexable=True),
                     Column(name='user_id', fb_type='int', sqlite_type='INTEGER', indexable=True),
                     Column(name='object_type', fb_type='string', sqlite_type='TEXT', indexable=False)),
            'link': (Column(name='link_id', fb_type='int', sqlite_type='INTEGER', indexable=True),
                     Column(name='owner', fb_type='int', sqlite_type='INTEGER', indexable=True),
                     Column(name='owner_comment', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='created_time', fb_type='int', sqlite_type='INTEGER', indexable=False),
                     Column(name='title', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='summary', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='url', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='picture', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='image_urls', fb_type='array', sqlite_type='', indexable=False)),
            'link_stat': (Column(name='url', fb_type='string', sqlite_type='TEXT', indexable=True),
                          Column(name='normalized_url', fb_type='string', sqlite_type='TEXT', indexable=False),
                          Column(name='share_count', fb_type='int', sqlite_type='INTEGER', indexable=False),
                          Column(name='like_count', fb_type='int', sqlite_type='INTEGER', indexable=False),
                          Column(name='comment_count', fb_type='int', sqlite_type='INTEGER', indexable=False),
                          Column(name='total_count', fb_type='int', sqlite_type='INTEGER', indexable=False),
                          Column(name='click_count', fb_type='int', sqlite_type='INTEGER', indexable=False),
                          Column(name='comments_fbid', fb_type='int', sqlite_type='INTEGER', indexable=False),
                          Column(name='commentsbox_count', fb_type='int', sqlite_type='INTEGER', indexable=False)),
            'mailbox_folder': (Column(name='folder_id', fb_type='string', sqlite_type='TEXT', indexable=True),
                               Column(name='viewer_id', fb_type='int', sqlite_type='INTEGER', indexable=True),
                               Column(name='name', fb_type='string', sqlite_type='TEXT', indexable=False),
                               Column(name='unread_count', fb_type='int', sqlite_type='INTEGER', indexable=False),
                               Column(name='total_count', fb_type='int', sqlite_type='INTEGER', indexable=False)),
            'message': (Column(name='message_id', fb_type='string', sqlite_type='TEXT', indexable=True),
                        Column(name='thread_id', fb_type='string', sqlite_type='TEXT', indexable=True),
                        Column(name='author_id', fb_type='int', sqlite_type='INTEGER', indexable=False),
                        Column(name='body', fb_type='string', sqlite_type='TEXT', indexable=False),
                        Column(name='created_time', fb_type='int', sqlite_type='INTEGER', indexable=False),
                        Column(name='attachment', fb_type='array', sqlite_type='', indexable=False),
                        Column(name='viewer_id', fb_type='string', sqlite_type='TEXT', indexable=False)),
            'note': (Column(name='uid', fb_type='int', sqlite_type='INTEGER', indexable=True),
                     Column(name='note_id', fb_type='string', sqlite_type='TEXT', indexable=True),
                     Column(name='created_time', fb_type='int', sqlite_type='INTEGER', indexable=False),
                     Column(name='updated_time', fb_type='int', sqlite_type='INTEGER', indexable=False),
                     Column(name='content', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='content_html', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='title', fb_type='string', sqlite_type='TEXT', indexable=False)),
            'notification': (Column(name='notification_id', fb_type='string', sqlite_type='TEXT', indexable=False),
                             Column(name='sender_id', fb_type='int', sqlite_type='INTEGER', indexable=False),
                             Column(name='recipient_id', fb_type='int', sqlite_type='INTEGER', indexable=True),
                             Column(name='created_time', fb_type='int', sqlite_type='INTEGER', indexable=False),
                             Column(name='updated_time', fb_type='int', sqlite_type='INTEGER', indexable=False),
                             Column(name='title_html', fb_type='string', sqlite_type='TEXT', indexable=False),
                             Column(name='title_text', fb_type='string', sqlite_type='TEXT', indexable=False),
                             Column(name='body_html', fb_type='string', sqlite_type='TEXT', indexable=False),
                             Column(name='body_text', fb_type='string', sqlite_type='TEXT', indexable=False),
                             Column(name='href', fb_type='string', sqlite_type='TEXT', indexable=False),
                             Column(name='app_id', fb_type='int', sqlite_type='INTEGER', indexable=False),
                             Column(name='is_unread', fb_type='bool', sqlite_type='INTEGER', indexable=False),
                             Column(name='is_hidden', fb_type='bool', sqlite_type='INTEGER', indexable=False),
                             Column(name='object_id', fb_type='string', sqlite_type='TEXT', indexable=False),
                             Column(name='object_type', fb_type='string', sqlite_type='TEXT', indexable=False),
                             Column(name='icon_url', fb_type='string', sqlite_type='TEXT', indexable=False)),
            'object_url': (Column(name='url', fb_type='string', sqlite_type='TEXT', indexable=True),
                           Column(name='id', fb_type='int', sqlite_type='INTEGER', indexable=True),
                           Column(name='type', fb_type='string', sqlite_type='TEXT', indexable=False),
                           Column(name='site', fb_type='string', sqlite_type='TEXT', indexable=False)),
            'page': (Column(name='page_id', fb_type='int', sqlite_type='INTEGER', indexable=True),
                     Column(name='name', fb_type='string', sqlite_type='TEXT', indexable=True),
                     Column(name='username', fb_type='string', sqlite_type='TEXT', indexable=True),
                     Column(name='description', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='categories', fb_type='array', sqlite_type='', indexable=False),
                     Column(name='is_community_page', fb_type='bool', sqlite_type='INTEGER', indexable=False),
                     Column(name='pic_small', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='pic_big', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='pic_square', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='pic', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='pic_large', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='page_url', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='fan_count', fb_type='int', sqlite_type='INTEGER', indexable=False),
                     Column(name='type', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='website', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='has_added_app', fb_type='bool', sqlite_type='INTEGER', indexable=False),
                     Column(name='general_info', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='can_post', fb_type='bool', sqlite_type='INTEGER', indexable=False),
                     Column(name='checkins', fb_type='int', sqlite_type='INTEGER', indexable=False),
                     Column(name='founded', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='company_overview', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='mission', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='products', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='location', fb_type='object', sqlite_type='', indexable=False),
                     Column(name='parking', fb_type='object', sqlite_type='', indexable=False),
                     Column(name='hours', fb_type='object', sqlite_type='', indexable=False),
                     Column(name='pharma_safety_info', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='public_transit', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='attire', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='payment_options', fb_type='array', sqlite_type='', indexable=False),
                     Column(name='culinary_team', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='general_manager', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='price_range', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='restaurant_services', fb_type='array', sqlite_type='', indexable=False),
                     Column(name='restaurant_specialties', fb_type='array', sqlite_type='', indexable=False),
                     Column(name='phone', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='release_date', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='genre', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='starring', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='screenplay_by', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='directed_by', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='produced_by', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='studio', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='awards', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='plot_outline', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='season', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='network', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='schedule', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='written_by', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='band_members', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='hometown', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='current_location', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='record_label', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='booking_agent', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='press_contact', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='artists_we_like', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='influences', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='band_interests', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='bio', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='affiliation', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='birthday', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='personal_info', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='personal_interests', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='built', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='features', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='mpg', fb_type='string', sqlite_type='TEXT', indexable=False)),
            'page_admin': (Column(name='uid', fb_type='string', sqlite_type='TEXT', indexable=True),
                           Column(name='page_id', fb_type='string', sqlite_type='TEXT', indexable=True),
                           Column(name='type', fb_type='string', sqlite_type='TEXT', indexable=False)),
            'page_blocked_user': (Column(name='page_id', fb_type='string', sqlite_type='TEXT', indexable=True),
                                  Column(name='uid', fb_type='string', sqlite_type='TEXT', indexable=False)),
            'page_fan': (Column(name='uid', fb_type='int', sqlite_type='INTEGER', indexable=True),
                         Column(name='page_id', fb_type='int', sqlite_type='INTEGER', indexable=False),
                         Column(name='type', fb_type='string', sqlite_type='TEXT', indexable=False),
                         Column(name='profile_section', fb_type='string', sqlite_type='TEXT', indexable=False),
                         Column(name='created_time', fb_type='int', sqlite_type='INTEGER', indexable=False)),
            'permissions_info': (Column(name='permission_name', fb_type='string', sqlite_type='TEXT', indexable=True),
                                 Column(name='header', fb_type='string', sqlite_type='TEXT', indexable=False),
                                 Column(name='summary', fb_type='string', sqlite_type='TEXT', indexable=False)),
            'photo': (Column(name='pid', fb_type='string', sqlite_type='TEXT', indexable=True),
                      Column(name='aid', fb_type='string', sqlite_type='TEXT', indexable=True),
                      Column(name='owner', fb_type='string', sqlite_type='TEXT', indexable=False),
                      Column(name='src_small', fb_type='string', sqlite_type='TEXT', indexable=False),
                      Column(name='src_small_width', fb_type='int', sqlite_type='INTEGER', indexable=False),
                      Column(name='src_small_height', fb_type='int', sqlite_type='INTEGER', indexable=False),
                      Column(name='src_big', fb_type='string', sqlite_type='TEXT', indexable=False),
                      Column(name='src_big_width', fb_type='int', sqlite_type='INTEGER', indexable=False),
                      Column(name='src_big_height', fb_type='int', sqlite_type='INTEGER', indexable=False),
                      Column(name='src', fb_type='string', sqlite_type='TEXT', indexable=False),
                      Column(name='src_width', fb_type='int', sqlite_type='INTEGER', indexable=False),
                      Column(name='src_height', fb_type='int', sqlite_type='INTEGER', indexable=False),
                      Column(name='link', fb_type='string', sqlite_type='TEXT', indexable=False),
                      Column(name='caption', fb_type='string', sqlite_type='TEXT', indexable=False),
                      Column(name='created', fb_type='int', sqlite_type='INTEGER', indexable=False),
                      Column(name='modified', fb_type='int', sqlite_type='INTEGER', indexable=False),
                      Column(name='position', fb_type='int', sqlite_type='INTEGER', indexable=False),
                      Column(name='object_id', fb_type='int', sqlite_type='INTEGER', indexable=True),
                      Column(name='album_object_id', fb_type='int', sqlite_type='INTEGER', indexable=True),
                      Column(name='images', fb_type='array', sqlite_type='', indexable=False)),
            'photo_tag': (Column(name='pid', fb_type='string', sqlite_type='TEXT', indexable=True),
                          Column(name='subject', fb_type='string', sqlite_type='TEXT', indexable=True),
                          Column(name='object_id', fb_type='int', sqlite_type='INTEGER', indexable=False),
                          Column(name='text', fb_type='string', sqlite_type='TEXT', indexable=False),
                          Column(name='xcoord', fb_type='float', sqlite_type='REAL', indexable=False),
                          Column(name='ycoord', fb_type='float', sqlite_type='REAL', indexable=False),
                          Column(name='created', fb_type='int', sqlite_type='INTEGER', indexable=False)),
            'place': (Column(name='page_id', fb_type='int', sqlite_type='INTEGER', indexable=True),
                      Column(name='name', fb_type='string', sqlite_type='TEXT', indexable=False),
                      Column(name='description', fb_type='string', sqlite_type='TEXT', indexable=False),
                      Column(name='geometry', fb_type='array', sqlite_type='', indexable=False),
                      Column(name='latitude', fb_type='int', sqlite_type='INTEGER', indexable=False),
                      Column(name='longitude', fb_type='int', sqlite_type='INTEGER', indexable=False),
                      Column(name='checkin_count', fb_type='int', sqlite_type='INTEGER', indexable=False),
                      Column(name='display_subtext', fb_type='string', sqlite_type='TEXT', indexable=False)),
            'privacy': (Column(name='id', fb_type='int', sqlite_type='INTEGER', indexable=True),
                        Column(name='object_id', fb_type='int', sqlite_type='INTEGER', indexable=True),
                        Column(name='value', fb_type='string', sqlite_type='TEXT', indexable=False),
                        Column(name='description', fb_type='string', sqlite_type='TEXT', indexable=False),
                        Column(name='allow', fb_type='string', sqlite_type='TEXT', indexable=False),
                        Column(name='deny', fb_type='string', sqlite_type='TEXT', indexable=False),
                        Column(name='owner_id', fb_type='int', sqlite_type='INTEGER', indexable=False),
                        Column(name='networks', fb_type='int', sqlite_type='INTEGER', indexable=False),
                        Column(name='friends', fb_type='string', sqlite_type='TEXT', indexable=False)),
            'privacy_setting': (Column(name='name', fb_type='string', sqlite_type='TEXT', indexable=True),
                                Column(name='value', fb_type='string', sqlite_type='TEXT', indexable=False),
                                Column(name='description', fb_type='string', sqlite_type='TEXT', indexable=False),
                                Column(name='allow', fb_type='string', sqlite_type='TEXT', indexable=False),
                                Column(name='deny', fb_type='string', sqlite_type='TEXT', indexable=False),
                                Column(name='networks', fb_type='int', sqlite_type='INTEGER', indexable=False),
                                Column(name='friends', fb_type='string', sqlite_type='TEXT', indexable=False)),
            'profile': (Column(name='id', fb_type='int', sqlite_type='INTEGER', indexable=True),
                        Column(name='can_post', fb_type='bool', sqlite_type='INTEGER', indexable=False),
                        Column(name='name', fb_type='string', sqlite_type='TEXT', indexable=False),
                        Column(name='url', fb_type='string', sqlite_type='TEXT', indexable=False),
                        Column(name='pic', fb_type='string', sqlite_type='TEXT', indexable=False),
                        Column(name='pic_square', fb_type='string', sqlite_type='TEXT', indexable=False),
                        Column(name='pic_small', fb_type='string', sqlite_type='TEXT', indexable=False),
                        Column(name='pic_big', fb_type='string', sqlite_type='TEXT', indexable=False),
                        Column(name='pic_crop', fb_type='object', sqlite_type='', indexable=False),
                        Column(name='type', fb_type='string', sqlite_type='TEXT', indexable=False),
                        Column(name='username', fb_type='string', sqlite_type='TEXT', indexable=True)),
            'question': (Column(name='id', fb_type='int', sqlite_type='INTEGER', indexable=True),
                         Column(name='owner', fb_type='int', sqlite_type='INTEGER', indexable=True),
                         Column(name='question', fb_type='string', sqlite_type='TEXT', indexable=False),
                         Column(name='created_time', fb_type='int', sqlite_type='INTEGER', indexable=False),
                         Column(name='updated_time', fb_type='int', sqlite_type='INTEGER', indexable=False)),
            'question_option': (Column(name='id', fb_type='int', sqlite_type='INTEGER', indexable=True),
                                Column(name='question_id', fb_type='string', sqlite_type='TEXT', indexable=True),
                                Column(name='name', fb_type='string', sqlite_type='TEXT', indexable=False),
                                Column(name='votes', fb_type='int', sqlite_type='INTEGER', indexable=False),
                                Column(name='object_id', fb_type='int', sqlite_type='INTEGER', indexable=False),
                                Column(name='owner', fb_type='int', sqlite_type='INTEGER', indexable=False),
                                Column(name='created_time', fb_type='int', sqlite_type='INTEGER', indexable=False)),
            'question_option_votes': (Column(name='option_id', fb_type='int', sqlite_type='INTEGER', indexable=True),
                                      Column(name='voter_id', fb_type='int', sqlite_type='INTEGER', indexable=False)),
            'review': (Column(name='reviewee_id', fb_type='int', sqlite_type='INTEGER', indexable=True),
                       Column(name='reviewer_id', fb_type='int', sqlite_type='INTEGER', indexable=True),
                       Column(name='review_id', fb_type='int', sqlite_type='INTEGER', indexable=False),
                       Column(name='message', fb_type='string', sqlite_type='TEXT', indexable=False),
                       Column(name='created_time', fb_type='int', sqlite_type='INTEGER', indexable=False),
                       Column(name='rating', fb_type='int', sqlite_type='INTEGER', indexable=False)),
            'standard_friend_info': (Column(name='uid1', fb_type='int', sqlite_type='INTEGER', indexable=True),
                                     Column(name='uid2', fb_type='int', sqlite_type='INTEGER', indexable=True)),
            'standard_user_info': (Column(name='uid', fb_type='string', sqlite_type='TEXT', indexable=True),
                                   Column(name='name', fb_type='string', sqlite_type='TEXT', indexable=True),
                                   Column(name='username', fb_type='string', sqlite_type='TEXT', indexable=True),
                                   Column(name='third_party_id', fb_type='string', sqlite_type='TEXT', indexable=True),
                                   Column(name='first_name', fb_type='string', sqlite_type='TEXT', indexable=False),
                                   Column(name='last_name', fb_type='string', sqlite_type='TEXT', indexable=False),
                                   Column(name='locale', fb_type='string', sqlite_type='TEXT', indexable=False),
                                   Column(name='affiliations', fb_type='array', sqlite_type='', indexable=False),
                                   Column(name='profile_url', fb_type='string', sqlite_type='TEXT', indexable=False),
                                   Column(name='timezone', fb_type='string', sqlite_type='TEXT', indexable=False),
                                   Column(name='birthday', fb_type='string', sqlite_type='TEXT', indexable=False),
                                   Column(name='sex', fb_type='string', sqlite_type='TEXT', indexable=False),
                                   Column(name='proxied_email', fb_type='string', sqlite_type='TEXT', indexable=False),
                                   Column(name='current_location', fb_type='string', sqlite_type='TEXT', indexable=False),
                                   Column(name='allowed_restrictions', fb_type='string', sqlite_type='TEXT', indexable=False)),
            'status': (Column(name='uid', fb_type='int', sqlite_type='INTEGER', indexable=True),
                       Column(name='status_id', fb_type='int', sqlite_type='INTEGER', indexable=True),
                       Column(name='time', fb_type='int', sqlite_type='INTEGER', indexable=False),
                       Column(name='source', fb_type='int', sqlite_type='INTEGER', indexable=False),
                       Column(name='message', fb_type='string', sqlite_type='TEXT', indexable=False)),
            'stream': (Column(name='post_id', fb_type='string', sqlite_type='TEXT', indexable=True),
                       Column(name='viewer_id', fb_type='int', sqlite_type='INTEGER', indexable=False),
                       Column(name='app_id', fb_type='int', sqlite_type='INTEGER', indexable=False),
                       Column(name='source_id', fb_type='int', sqlite_type='INTEGER', indexable=True),
                       Column(name='updated_time', fb_type='int', sqlite_type='INTEGER', indexable=False),
                       Column(name='created_time', fb_type='int', sqlite_type='INTEGER', indexable=False),
                       Column(name='filter_key', fb_type='string', sqlite_type='TEXT', indexable=True),
                       Column(name='attribution', fb_type='string', sqlite_type='TEXT', indexable=False),
                       Column(name='actor_id', fb_type='int', sqlite_type='INTEGER', indexable=False),
                       Column(name='target_id', fb_type='string', sqlite_type='TEXT', indexable=False),
                       Column(name='message', fb_type='string', sqlite_type='TEXT', indexable=False),
                       Column(name='app_data', fb_type='array', sqlite_type='', indexable=False),
                       Column(name='action_links', fb_type='array', sqlite_type='', indexable=False),
                       Column(name='attachment', fb_type='array', sqlite_type='', indexable=False),
                       Column(name='impressions', fb_type='int', sqlite_type='INTEGER', indexable=False),
                       Column(name='comments', fb_type='array', sqlite_type='', indexable=False),
                       Column(name='likes', fb_type='array', sqlite_type='', indexable=False),
                       Column(name='privacy', fb_type='array', sqlite_type='', indexable=False),
                       Column(name='permalink', fb_type='string', sqlite_type='TEXT', indexable=False),
                       Column(name='xid', fb_type='int', sqlite_type='INTEGER', indexable=True),
                       Column(name='tagged_ids', fb_type='array', sqlite_type='', indexable=False),
                       Column(name='message_tags', fb_type='array', sqlite_type='', indexable=False),
                       Column(name='description_tags', fb_type='array', sqlite_type='', indexable=False)),
            'stream_filter': (Column(name='uid', fb_type='int', sqlite_type='INTEGER', indexable=True),
                              Column(name='filter_key', fb_type='string', sqlite_type='TEXT', indexable=True),
                              Column(name='name', fb_type='string', sqlite_type='TEXT', indexable=False),
                              Column(name='rank', fb_type='int', sqlite_type='INTEGER', indexable=False),
                              Column(name='icon_url', fb_type='string', sqlite_type='TEXT', indexable=False),
                              Column(name='is_visible', fb_type='bool', sqlite_type='INTEGER', indexable=False),
                              Column(name='type', fb_type='string', sqlite_type='TEXT', indexable=False),
                              Column(name='value', fb_type='int', sqlite_type='INTEGER', indexable=False)),
            'stream_tag': (Column(name='post_id', fb_type='string', sqlite_type='TEXT', indexable=True),
                           Column(name='actor_id', fb_type='string', sqlite_type='TEXT', indexable=True),
                           Column(name='target_id', fb_type='string', sqlite_type='TEXT', indexable=True)),
            'thread': (Column(name='thread_id', fb_type='string', sqlite_type='TEXT', indexable=True),
                       Column(name='folder_id', fb_type='string', sqlite_type='TEXT', indexable=True),
                       Column(name='subject', fb_type='string', sqlite_type='TEXT', indexable=False),
                       Column(name='recipients', fb_type='array', sqlite_type='', indexable=False),
                       Column(name='updated_time', fb_type='int', sqlite_type='INTEGER', indexable=False),
                       Column(name='parent_message_id', fb_type='string', sqlite_type='TEXT', indexable=False),
                       Column(name='parent_thread_id', fb_type='int', sqlite_type='INTEGER', indexable=False),
                       Column(name='message_count', fb_type='int', sqlite_type='INTEGER', indexable=False),
                       Column(name='snippet', fb_type='string', sqlite_type='TEXT', indexable=False),
                       Column(name='snippet_author', fb_type='int', sqlite_type='INTEGER', indexable=False),
                       Column(name='object_id', fb_type='int', sqlite_type='INTEGER', indexable=False),
                       Column(name='unread', fb_type='int', sqlite_type='INTEGER', indexable=False),
                       Column(name='viewer_id', fb_type='string', sqlite_type='TEXT', indexable=False)),
            'translation': (Column(name='locale', fb_type='string', sqlite_type='TEXT', indexable=True),
                            Column(name='native_hash', fb_type='string', sqlite_type='TEXT', indexable=True),
                            Column(name='native_string', fb_type='string', sqlite_type='TEXT', indexable=False),
                            Column(name='description', fb_type='string', sqlite_type='TEXT', indexable=False),
                            Column(name='translation', fb_type='string', sqlite_type='TEXT', indexable=False),
                            Column(name='approval_status', fb_type='string', sqlite_type='TEXT', indexable=False),
                            Column(name='pre_hash_string', fb_type='string', sqlite_type='TEXT', indexable=True),
                            Column(name='best_string', fb_type='string', sqlite_type='TEXT', indexable=False)),
            'unified_message': (Column(name='message_id', fb_type='string', sqlite_type='TEXT', indexable=True),
                                Column(name='thread_id', fb_type='string', sqlite_type='TEXT', indexable=True),
                                Column(name='subject', fb_type='string', sqlite_type='TEXT', indexable=False),
                                Column(name='body', fb_type='string', sqlite_type='TEXT', indexable=False),
                                Column(name='unread', fb_type='bool', sqlite_type='INTEGER', indexable=True),
                                Column(name='action_id', fb_type='string', sqlite_type='TEXT', indexable=False),
                                Column(name='timestamp', fb_type='string', sqlite_type='TEXT', indexable=True),
                                Column(name='tags', fb_type='array', sqlite_type='', indexable=False),
                                Column(name='sender', fb_type='object', sqlite_type='', indexable=False),
                                Column(name='recipients', fb_type='array', sqlite_type='', indexable=False),
                                Column(name='object_sender', fb_type='object', sqlite_type='', indexable=False),
                                Column(name='html_body', fb_type='string', sqlite_type='TEXT', indexable=False),
                                Column(name='attachments', fb_type='array', sqlite_type='', indexable=False),
                                Column(name='attachment_map', fb_type='array', sqlite_type='', indexable=False),
                                Column(name='shares', fb_type='array', sqlite_type='', indexable=False),
                                Column(name='share_map', fb_type='array', sqlite_type='', indexable=False)),
            'unified_thread': (Column(name='action_id', fb_type='string', sqlite_type='TEXT', indexable=False),
                               Column(name='archived', fb_type='bool', sqlite_type='INTEGER', indexable=True),
                               Column(name='can_reply', fb_type='bool', sqlite_type='INTEGER', indexable=False),
                               Column(name='folder', fb_type='string', sqlite_type='TEXT', indexable=True),
                               Column(name='former_participants', fb_type='array', sqlite_type='', indexable=False),
                               Column(name='has_attachments', fb_type='bool', sqlite_type='INTEGER', indexable=False),
                               Column(name='is_subscribed', fb_type='bool', sqlite_type='INTEGER', indexable=False),
                               Column(name='last_visible_add_action_id', fb_type='string', sqlite_type='TEXT', indexable=False),
                               Column(name='name', fb_type='string', sqlite_type='TEXT', indexable=False),
                               Column(name='num_messages', fb_type='int', sqlite_type='INTEGER', indexable=False),
                               Column(name='num_unread', fb_type='int', sqlite_type='INTEGER', indexable=False),
                               Column(name='object_participants', fb_type='array', sqlite_type='', indexable=False),
                               Column(name='participants', fb_type='array', sqlite_type='', indexable=False),
                               Column(name='senders', fb_type='array', sqlite_type='', indexable=False),
                               Column(name='single_recipient', fb_type='string', sqlite_type='TEXT', indexable=True),
                               Column(name='snippet', fb_type='string', sqlite_type='TEXT', indexable=False),
                               Column(name='snippet_sender', fb_type='array', sqlite_type='', indexable=False),
                               Column(name='snippet_message_has_attachment', fb_type='bool', sqlite_type='INTEGER', indexable=False),
                               Column(name='subject', fb_type='string', sqlite_type='TEXT', indexable=False),
                               Column(name='tags', fb_type='array', sqlite_type='', indexable=False),
                               Column(name='thread_id', fb_type='string', sqlite_type='TEXT', indexable=True),
                               Column(name='thread_participants', fb_type='array', sqlite_type='', indexable=False),
                               Column(name='timestamp', fb_type='string', sqlite_type='TEXT', indexable=True),
                               Column(name='unread', fb_type='bool', sqlite_type='INTEGER', indexable=True)),
            'unified_thread_action': (Column(name='action_id', fb_type='string', sqlite_type='TEXT', indexable=False),
                                      Column(name='actor', fb_type='object', sqlite_type='', indexable=False),
                                      Column(name='thread_id', fb_type='string', sqlite_type='TEXT', indexable=True),
                                      Column(name='timestamp', fb_type='string', sqlite_type='TEXT', indexable=False),
                                      Column(name='type', fb_type='int', sqlite_type='INTEGER', indexable=False),
                                      Column(name='users', fb_type='array', sqlite_type='', indexable=False)),
            'unified_thread_count': (Column(name='folder', fb_type='string', sqlite_type='TEXT', indexable=True),
                                     Column(name='unread_count', fb_type='int', sqlite_type='INTEGER', indexable=True),
                                     Column(name='unseen_count', fb_type='int', sqlite_type='INTEGER', indexable=True),
                                     Column(name='last_action_id', fb_type='int', sqlite_type='INTEGER', indexable=True),
                                     Column(name='last_seen_time', fb_type='int', sqlite_type='INTEGER', indexable=True),
                                     Column(name='total_threads', fb_type='int', sqlite_type='INTEGER', indexable=True)),
            'url_like': (Column(name='user_id', fb_type='string', sqlite_type='TEXT', indexable=True),
                         Column(name='url', fb_type='string', sqlite_type='TEXT', indexable=False)),
            'user': (Column(name='uid', fb_type='int', sqlite_type='INTEGER', indexable=True),
                     Column(name='username', fb_type='string', sqlite_type='TEXT', indexable=True),
                     Column(name='first_name', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='middle_name', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='last_name', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='name', fb_type='string', sqlite_type='TEXT', indexable=True),
                     Column(name='pic_small', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='pic_big', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='pic_square', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='pic', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='affiliations', fb_type='array', sqlite_type='', indexable=False),
                     Column(name='profile_update_time', fb_type='int', sqlite_type='INTEGER', indexable=False),
                     Column(name='timezone', fb_type='int', sqlite_type='INTEGER', indexable=False),
                     Column(name='religion', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='birthday', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='birthday_date', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='sex', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='hometown_location', fb_type='array', sqlite_type='', indexable=False),
                     Column(name='meeting_sex', fb_type='array', sqlite_type='', indexable=False),
                     Column(name='meeting_for', fb_type='array', sqlite_type='', indexable=False),
                     Column(name='relationship_status', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='significant_other_id', fb_type='int', sqlite_type='INTEGER', indexable=False),
                     Column(name='political', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='current_location', fb_type='array', sqlite_type='', indexable=False),
                     Column(name='activities', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='interests', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='is_app_user', fb_type='bool', sqlite_type='INTEGER', indexable=False),
                     Column(name='music', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='tv', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='movies', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='books', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='quotes', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='about_me', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='hs_info', fb_type='array', sqlite_type='', indexable=False),
                     Column(name='education_history', fb_type='array', sqlite_type='', indexable=False),
                     Column(name='work_history', fb_type='array', sqlite_type='', indexable=False),
                     Column(name='notes_count', fb_type='int', sqlite_type='INTEGER', indexable=False),
                     Column(name='wall_count', fb_type='int', sqlite_type='INTEGER', indexable=False),
                     Column(name='status', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='has_added_app', fb_type='bool', sqlite_type='INTEGER', indexable=False),
                     Column(name='online_presence', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='locale', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='proxied_email', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='profile_url', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='email_hashes', fb_type='array', sqlite_type='', indexable=False),
                     Column(name='pic_small_with_logo', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='pic_big_with_logo', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='pic_square_with_logo', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='pic_with_logo', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='allowed_restrictions', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='verified', fb_type='bool', sqlite_type='INTEGER', indexable=False),
                     Column(name='profile_blurb', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='family', fb_type='array', sqlite_type='', indexable=False),
                     Column(name='website', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='is_blocked', fb_type='bool', sqlite_type='INTEGER', indexable=False),
                     Column(name='contact_email', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='email', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='third_party_id', fb_type='string', sqlite_type='TEXT', indexable=True),
                     Column(name='name_format', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='video_upload_limits', fb_type='array', sqlite_type='', indexable=False),
                     Column(name='games', fb_type='string', sqlite_type='TEXT', indexable=False),
                     Column(name='is_minor', fb_type='bool', sqlite_type='INTEGER', indexable=False),
                     Column(name='work', fb_type='array', sqlite_type='', indexable=False),
                     Column(name='education', fb_type='array', sqlite_type='', indexable=False),
                     Column(name='sports', fb_type='array', sqlite_type='', indexable=False),
                     Column(name='favorite_athletes', fb_type='array', sqlite_type='', indexable=False),
                     Column(name='favorite_teams', fb_type='array', sqlite_type='', indexable=False),
                     Column(name='inspirational_people', fb_type='array', sqlite_type='', indexable=False),
                     Column(name='languages', fb_type='array', sqlite_type='', indexable=False),
                     Column(name='likes_count', fb_type='int', sqlite_type='INTEGER', indexable=False),
                     Column(name='friend_count', fb_type='int', sqlite_type='INTEGER', indexable=False),
                     Column(name='mutual_friend_count', fb_type='int', sqlite_type='INTEGER', indexable=False),
                     Column(name='can_post', fb_type='bool', sqlite_type='INTEGER', indexable=False)),
            'video': (Column(name='vid', fb_type='int', sqlite_type='INTEGER', indexable=True),
                      Column(name='owner', fb_type='int', sqlite_type='INTEGER', indexable=True),
                      Column(name='album_id', fb_type='int', sqlite_type='INTEGER', indexable=True),
                      Column(name='title', fb_type='string', sqlite_type='TEXT', indexable=False),
                      Column(name='description', fb_type='string', sqlite_type='TEXT', indexable=False),
                      Column(name='link', fb_type='string', sqlite_type='TEXT', indexable=False),
                      Column(name='thumbnail_link', fb_type='string', sqlite_type='TEXT', indexable=False),
                      Column(name='embed_html', fb_type='string', sqlite_type='TEXT', indexable=False),
                      Column(name='updated_time', fb_type='int', sqlite_type='INTEGER', indexable=False),
                      Column(name='created_time', fb_type='int', sqlite_type='INTEGER', indexable=False),
                      Column(name='length', fb_type='float', sqlite_type='REAL', indexable=False),
                      Column(name='src', fb_type='string', sqlite_type='TEXT', indexable=False),
                      Column(name='src_hq', fb_type='string', sqlite_type='TEXT', indexable=False)),
            'video_tag': (Column(name='vid', fb_type='string', sqlite_type='TEXT', indexable=True),
                          Column(name='subject', fb_type='int', sqlite_type='INTEGER', indexable=True),
                          Column(name='updated_time', fb_type='int', sqlite_type='INTEGER', indexable=False),
                          Column(name='created_time', fb_type='int', sqlite_type='INTEGER', indexable=False))}}
