# Do not edit! Generated automatically by mockfacebook.
# https://github.com/rogerhu/mockfacebook
# 2012-10-23 22:47:33.406235

{'connections': {u'application': [u'feed',
                                  u'picture',
                                  u'tagged',
                                  u'videos',
                                  u'links',
                                  u'subscriptions',
                                  u'notes',
                                  u'posts',
                                  u'photos',
                                  u'albums',
                                  u'events',
                                  u'statuses',
                                  u'insights'],
                 u'checkin': [u'likes', u'comments', u'tags'],
                 u'comment': [u'likes', u'comments'],
                 u'event': [u'feed',
                            u'picture',
                            u'noreply',
                            u'maybe',
                            u'invited',
                            u'attending',
                            u'admins',
                            u'declined'],
                 u'friendlist': [u'members'],
                 u'group': [u'feed',
                            u'picture',
                            u'files',
                            u'members',
                            u'docs'],
                 u'link': [u'likes', u'comments'],
                 u'normal': [u'photos',
                             u'likes',
                             u'comments',
                             u'sharedposts'],
                 u'note': [u'comments', u'sharedposts'],
                 u'page': [u'feed',
                           u'picture',
                           u'tagged',
                           u'milestones',
                           u'videos',
                           u'links',
                           u'notes',
                           u'posts',
                           u'global_brand_children',
                           u'photos',
                           u'offers',
                           u'questions',
                           u'albums',
                           u'events',
                           u'statuses'],
                 u'photo': [u'sharedposts', u'likes', u'comments', u'tags'],
                 u'status': [u'sharedposts', u'likes', u'comments', u'tags'],
                 u'user': [u'feed',
                           u'tagged',
                           u'subscribers',
                           u'family',
                           u'picture',
                           u'mutualfriends',
                           u'locations',
                           u'books',
                           u'accounts',
                           u'likes',
                           u'questions',
                           u'home',
                           u'statuses',
                           u'friendrequests',
                           u'links',
                           u'checkins',
                           u'subscribedto',
                           u'music',
                           u'videos',
                           u'events',
                           u'adaccounts',
                           u'interests',
                           u'activities',
                           u'apprequests',
                           u'photos',
                           u'updates',
                           u'groups',
                           u'scores',
                           u'friendlists',
                           u'outbox',
                           u'albums',
                           u'friends',
                           u'permissions',
                           u'television',
                           u'notifications',
                           u'notes',
                           u'posts',
                           u'movies',
                           u'games',
                           u'payments',
                           u'inbox'],
                 u'video': [u'likes', u'comments']},
 'tables': {u'application': [Column(name=u'id', fb_type='string', sqlite_type='TEXT', indexable=None),
                             Column(name=u'name', fb_type='string', sqlite_type='TEXT', indexable=None),
                             Column(name=u'description', fb_type='string', sqlite_type='TEXT', indexable=None),
                             Column(name=u'category', fb_type='string', sqlite_type='TEXT', indexable=None),
                             Column(name=u'company', fb_type='string', sqlite_type='TEXT', indexable=None),
                             Column(name=u'icon_url', fb_type='string', sqlite_type='TEXT', indexable=None),
                             Column(name=u'subcategory', fb_type='string', sqlite_type='TEXT', indexable=None),
                             Column(name=u'link', fb_type='string', sqlite_type='TEXT', indexable=None),
                             Column(name=u'logo_url', fb_type='string', sqlite_type='TEXT', indexable=None),
                             Column(name=u'daily_active_users', fb_type='string', sqlite_type='TEXT', indexable=None),
                             Column(name=u'weekly_active_users', fb_type='string', sqlite_type='TEXT', indexable=None),
                             Column(name=u'monthly_active_users', fb_type='string', sqlite_type='TEXT', indexable=None),
                             Column(name=u'migrations', fb_type='array', sqlite_type='', indexable=None),
                             Column(name=u'namespace', fb_type='string', sqlite_type='TEXT', indexable=None),
                             Column(name=u'restrictions', fb_type='object', sqlite_type='', indexable=None),
                             Column(name=u'app_domains', fb_type='array', sqlite_type='', indexable=None),
                             Column(name=u'auth_dialog_data_help_url', fb_type='string', sqlite_type='TEXT', indexable=None),
                             Column(name=u'auth_dialog_description', fb_type='string', sqlite_type='TEXT', indexable=None),
                             Column(name=u'auth_dialog_headline', fb_type='string', sqlite_type='TEXT', indexable=None),
                             Column(name=u'auth_dialog_perms_explanation', fb_type='string', sqlite_type='TEXT', indexable=None),
                             Column(name=u'auth_referral_user_perms', fb_type='array', sqlite_type='', indexable=None),
                             Column(name=u'auth_referral_friend_perms', fb_type='array', sqlite_type='', indexable=None),
                             Column(name=u'auth_referral_default_activity_privacy', fb_type='string', sqlite_type='TEXT', indexable=None),
                             Column(name=u'auth_referral_enabled', fb_type='bool', sqlite_type='INTEGER', indexable=None),
                             Column(name=u'auth_referral_extended_perms', fb_type='array', sqlite_type='', indexable=None),
                             Column(name=u'auth_referral_response_type', fb_type='string', sqlite_type='TEXT', indexable=None),
                             Column(name=u'canvas_fluid_height', fb_type='bool', sqlite_type='INTEGER', indexable=None),
                             Column(name=u'canvas_fluid_width', fb_type='bool', sqlite_type='INTEGER', indexable=None),
                             Column(name=u'canvas_url', fb_type='string', sqlite_type='TEXT', indexable=None),
                             Column(name=u'contact_email', fb_type='string', sqlite_type='TEXT', indexable=None),
                             Column(name=u'created_time', fb_type='int', sqlite_type='INTEGER', indexable=None),
                             Column(name=u'creator_uid', fb_type='int', sqlite_type='INTEGER', indexable=None),
                             Column(name=u'deauth_callback_url', fb_type='string', sqlite_type='TEXT', indexable=None),
                             Column(name=u'iphone_app_store_id', fb_type='string', sqlite_type='TEXT', indexable=None),
                             Column(name=u'hosting_url', fb_type='string', sqlite_type='TEXT', indexable=None),
                             Column(name=u'mobile_web_url', fb_type='string', sqlite_type='TEXT', indexable=None),
                             Column(name=u'page_tab_default_name', fb_type='string', sqlite_type='TEXT', indexable=None),
                             Column(name=u'page_tab_url', fb_type='string', sqlite_type='TEXT', indexable=None),
                             Column(name=u'privacy_policy_url', fb_type='string', sqlite_type='TEXT', indexable=None),
                             Column(name=u'secure_canvas_url', fb_type='string', sqlite_type='TEXT', indexable=None),
                             Column(name=u'secure_page_tab_url', fb_type='string', sqlite_type='TEXT', indexable=None),
                             Column(name=u'server_ip_whitelist', fb_type='string', sqlite_type='TEXT', indexable=None),
                             Column(name=u'social_discovery', fb_type='bool', sqlite_type='INTEGER', indexable=None),
                             Column(name=u'terms_of_service_url', fb_type='string', sqlite_type='TEXT', indexable=None),
                             Column(name=u'user_support_email', fb_type='string', sqlite_type='TEXT', indexable=None),
                             Column(name=u'user_support_url', fb_type='string', sqlite_type='TEXT', indexable=None),
                             Column(name=u'website_url', fb_type='string', sqlite_type='TEXT', indexable=None)],
            u'checkin': [Column(name=u'id', fb_type='string', sqlite_type='TEXT', indexable=None),
                         Column(name=u'from', fb_type='object', sqlite_type='', indexable=None),
                         Column(name=u'tags', fb_type='array', sqlite_type='', indexable=None),
                         Column(name=u'place', fb_type='object', sqlite_type='', indexable=None),
                         Column(name=u'application', fb_type='object', sqlite_type='', indexable=None),
                         Column(name=u'created_time', fb_type='string', sqlite_type='TEXT', indexable=None),
                         Column(name=u'likes', fb_type='array', sqlite_type='', indexable=None),
                         Column(name=u'message', fb_type='string', sqlite_type='TEXT', indexable=None),
                         Column(name=u'comments', fb_type='array', sqlite_type='', indexable=None),
                         Column(name=u'type', fb_type='string', sqlite_type='TEXT', indexable=None)],
            u'comment': [Column(name=u'id', fb_type='string', sqlite_type='TEXT', indexable=None),
                         Column(name=u'from', fb_type='object', sqlite_type='', indexable=None),
                         Column(name=u'message', fb_type='string', sqlite_type='TEXT', indexable=None),
                         Column(name=u'created_time', fb_type='string', sqlite_type='TEXT', indexable=None),
                         Column(name=u'likes', fb_type='int', sqlite_type='INTEGER', indexable=None),
                         Column(name=u'user_likes', fb_type='string', sqlite_type='TEXT', indexable=None),
                         Column(name=u'type', fb_type='string', sqlite_type='TEXT', indexable=None)],
            u'domain': [Column(name=u'id', fb_type='string', sqlite_type='TEXT', indexable=None),
                        Column(name=u'name', fb_type='string', sqlite_type='TEXT', indexable=None)],
            u'event': [Column(name=u'id', fb_type='string', sqlite_type='TEXT', indexable=None),
                       Column(name=u'owner', fb_type='object', sqlite_type='', indexable=None),
                       Column(name=u'name', fb_type='string', sqlite_type='TEXT', indexable=None),
                       Column(name=u'description', fb_type='string', sqlite_type='TEXT', indexable=None),
                       Column(name=u'start_time', fb_type='string', sqlite_type='TEXT', indexable=None),
                       Column(name=u'end_time', fb_type='string', sqlite_type='TEXT', indexable=None),
                       Column(name=u'location', fb_type='string', sqlite_type='TEXT', indexable=None),
                       Column(name=u'venue', fb_type='object', sqlite_type='', indexable=None),
                       Column(name=u'privacy', fb_type='string', sqlite_type='TEXT', indexable=None),
                       Column(name=u'updated_time', fb_type='string', sqlite_type='TEXT', indexable=None),
                       Column(name=u'picture', fb_type='string', sqlite_type='TEXT', indexable=None)],
            u'friendlist': [Column(name=u'id', fb_type='string', sqlite_type='TEXT', indexable=None),
                            Column(name=u'name', fb_type='string', sqlite_type='TEXT', indexable=None),
                            Column(name=u'list_type', fb_type='string', sqlite_type='TEXT', indexable=None)],
            u'group': [Column(name=u'id', fb_type='string', sqlite_type='TEXT', indexable=None),
                       Column(name=u'version', fb_type='int', sqlite_type='INTEGER', indexable=None),
                       Column(name=u'icon', fb_type='string', sqlite_type='TEXT', indexable=None),
                       Column(name=u'owner', fb_type='object', sqlite_type='', indexable=None),
                       Column(name=u'name', fb_type='string', sqlite_type='TEXT', indexable=None),
                       Column(name=u'description', fb_type='string', sqlite_type='TEXT', indexable=None),
                       Column(name=u'link', fb_type='string', sqlite_type='TEXT', indexable=None),
                       Column(name=u'privacy', fb_type='string', sqlite_type='TEXT', indexable=None),
                       Column(name=u'updated_time', fb_type='string', sqlite_type='TEXT', indexable=None)],
            u'normal': [Column(name=u'id', fb_type='string', sqlite_type='TEXT', indexable=None),
                        Column(name=u'from', fb_type='object', sqlite_type='', indexable=None),
                        Column(name=u'name', fb_type='string', sqlite_type='TEXT', indexable=None),
                        Column(name=u'description', fb_type='string', sqlite_type='TEXT', indexable=None),
                        Column(name=u'location', fb_type='string', sqlite_type='TEXT', indexable=None),
                        Column(name=u'link', fb_type='string', sqlite_type='TEXT', indexable=None),
                        Column(name=u'cover_photo', fb_type='string', sqlite_type='TEXT', indexable=None),
                        Column(name=u'privacy', fb_type='string', sqlite_type='TEXT', indexable=None),
                        Column(name=u'count', fb_type='string', sqlite_type='TEXT', indexable=None),
                        Column(name=u'type', fb_type='string', sqlite_type='TEXT', indexable=None),
                        Column(name=u'created_time', fb_type='string', sqlite_type='TEXT', indexable=None),
                        Column(name=u'updated_time', fb_type='string', sqlite_type='TEXT', indexable=None),
                        Column(name=u'can_upload', fb_type='bool', sqlite_type='INTEGER', indexable=None)],
            u'note': [Column(name=u'id', fb_type='string', sqlite_type='TEXT', indexable=None),
                      Column(name=u'from', fb_type='object', sqlite_type='', indexable=None),
                      Column(name=u'subject', fb_type='string', sqlite_type='TEXT', indexable=None),
                      Column(name=u'message', fb_type='string', sqlite_type='TEXT', indexable=None),
                      Column(name=u'comments', fb_type='array', sqlite_type='', indexable=None),
                      Column(name=u'created_time', fb_type='string', sqlite_type='TEXT', indexable=None),
                      Column(name=u'updated_time', fb_type='string', sqlite_type='TEXT', indexable=None),
                      Column(name=u'icon', fb_type='string', sqlite_type='TEXT', indexable=None)],
            u'page': [Column(name=u'id', fb_type='string', sqlite_type='TEXT', indexable=None),
                      Column(name=u'name', fb_type='string', sqlite_type='TEXT', indexable=None),
                      Column(name=u'link', fb_type='string', sqlite_type='TEXT', indexable=None),
                      Column(name=u'category', fb_type='string', sqlite_type='TEXT', indexable=None),
                      Column(name=u'is_published', fb_type='bool', sqlite_type='INTEGER', indexable=None),
                      Column(name=u'can_post', fb_type='bool', sqlite_type='INTEGER', indexable=None),
                      Column(name=u'likes', fb_type='int', sqlite_type='INTEGER', indexable=None),
                      Column(name=u'location', fb_type='object', sqlite_type='', indexable=None),
                      Column(name=u'phone', fb_type='string', sqlite_type='TEXT', indexable=None),
                      Column(name=u'checkins', fb_type='int', sqlite_type='INTEGER', indexable=None),
                      Column(name=u'picture', fb_type='string', sqlite_type='TEXT', indexable=None),
                      Column(name=u'cover', fb_type=None, sqlite_type=None, indexable=None),
                      Column(name=u'website', fb_type='string', sqlite_type='TEXT', indexable=None),
                      Column(name=u'talking_about_count', fb_type='int', sqlite_type='INTEGER', indexable=None),
                      Column(name=u'global_brand_like_count', fb_type=None, sqlite_type=None, indexable=None),
                      Column(name=u'global_brand_talking_about_count', fb_type=None, sqlite_type=None, indexable=None),
                      Column(name=u'global_brand_parent_page', fb_type='object', sqlite_type='', indexable=None),
                      Column(name=u'access_token', fb_type='string', sqlite_type='TEXT', indexable=None)],
            u'photo': [Column(name=u'id', fb_type='string', sqlite_type='TEXT', indexable=None),
                       Column(name=u'from', fb_type='object', sqlite_type='', indexable=None),
                       Column(name=u'tags', fb_type='array', sqlite_type='', indexable=None),
                       Column(name=u'name', fb_type='string', sqlite_type='TEXT', indexable=None),
                       Column(name=u'name_tags', fb_type='array', sqlite_type='', indexable=None),
                       Column(name=u'icon', fb_type='string', sqlite_type='TEXT', indexable=None),
                       Column(name=u'picture', fb_type='string', sqlite_type='TEXT', indexable=None),
                       Column(name=u'source', fb_type='string', sqlite_type='TEXT', indexable=None),
                       Column(name=u'height', fb_type='int', sqlite_type='INTEGER', indexable=None),
                       Column(name=u'width', fb_type='int', sqlite_type='INTEGER', indexable=None),
                       Column(name=u'images', fb_type='array', sqlite_type='', indexable=None),
                       Column(name=u'link', fb_type='string', sqlite_type='TEXT', indexable=None),
                       Column(name=u'place', fb_type='object', sqlite_type='', indexable=None),
                       Column(name=u'created_time', fb_type='string', sqlite_type='TEXT', indexable=None),
                       Column(name=u'updated_time', fb_type='string', sqlite_type='TEXT', indexable=None),
                       Column(name=u'position', fb_type='int', sqlite_type='INTEGER', indexable=None)],
            u'status': [Column(name=u'id', fb_type='string', sqlite_type='TEXT', indexable=None),
                        Column(name=u'from', fb_type='object', sqlite_type='', indexable=None),
                        Column(name=u'message', fb_type='string', sqlite_type='TEXT', indexable=None),
                        Column(name=u'place', fb_type='object', sqlite_type='', indexable=None),
                        Column(name=u'updated_time', fb_type='string', sqlite_type='TEXT', indexable=None),
                        Column(name=u'type', fb_type='string', sqlite_type='TEXT', indexable=None)],
            u'user': [Column(name=u'id', fb_type='string', sqlite_type='TEXT', indexable=None),
                      Column(name=u'name', fb_type='string', sqlite_type='TEXT', indexable=None),
                      Column(name=u'first_name', fb_type='string', sqlite_type='TEXT', indexable=None),
                      Column(name=u'middle_name', fb_type='string', sqlite_type='TEXT', indexable=None),
                      Column(name=u'last_name', fb_type='string', sqlite_type='TEXT', indexable=None),
                      Column(name=u'gender', fb_type='string', sqlite_type='TEXT', indexable=None),
                      Column(name=u'locale', fb_type='string', sqlite_type='TEXT', indexable=None),
                      Column(name=u'languages', fb_type='array', sqlite_type='', indexable=None),
                      Column(name=u'link', fb_type='string', sqlite_type='TEXT', indexable=None),
                      Column(name=u'username', fb_type='string', sqlite_type='TEXT', indexable=None),
                      Column(name=u'third_party_id', fb_type='string', sqlite_type='TEXT', indexable=None),
                      Column(name=u'installed', fb_type='object', sqlite_type='', indexable=None),
                      Column(name=u'timezone', fb_type='int', sqlite_type='INTEGER', indexable=None),
                      Column(name=u'updated_time', fb_type='string', sqlite_type='TEXT', indexable=None),
                      Column(name=u'verified', fb_type='bool', sqlite_type='INTEGER', indexable=None),
                      Column(name=u'bio', fb_type='string', sqlite_type='TEXT', indexable=None),
                      Column(name=u'birthday', fb_type='string', sqlite_type='TEXT', indexable=None),
                      Column(name=u'cover', fb_type='array', sqlite_type='', indexable=None),
                      Column(name=u'currency', fb_type='object', sqlite_type='', indexable=None),
                      Column(name=u'devices', fb_type='array', sqlite_type='', indexable=None),
                      Column(name=u'education', fb_type='array', sqlite_type='', indexable=None),
                      Column(name=u'email', fb_type='string', sqlite_type='TEXT', indexable=None),
                      Column(name=u'hometown', fb_type='object', sqlite_type='', indexable=None),
                      Column(name=u'interested_in', fb_type='array', sqlite_type='', indexable=None),
                      Column(name=u'location', fb_type='object', sqlite_type='', indexable=None),
                      Column(name=u'political', fb_type='string', sqlite_type='TEXT', indexable=None),
                      Column(name=u'payment_pricepoints', fb_type='array', sqlite_type='', indexable=None),
                      Column(name=u'favorite_athletes', fb_type='array', sqlite_type='', indexable=None),
                      Column(name=u'favorite_teams', fb_type='array', sqlite_type='', indexable=None),
                      Column(name=u'picture', fb_type='string', sqlite_type='TEXT', indexable=None),
                      Column(name=u'quotes', fb_type='string', sqlite_type='TEXT', indexable=None),
                      Column(name=u'relationship_status', fb_type='string', sqlite_type='TEXT', indexable=None),
                      Column(name=u'religion', fb_type='string', sqlite_type='TEXT', indexable=None),
                      Column(name=u'security_settings', fb_type='object', sqlite_type='', indexable=None),
                      Column(name=u'significant_other', fb_type='object', sqlite_type='', indexable=None),
                      Column(name=u'video_upload_limits', fb_type='object', sqlite_type='', indexable=None),
                      Column(name=u'website', fb_type='string', sqlite_type='TEXT', indexable=None),
                      Column(name=u'work', fb_type='array', sqlite_type='', indexable=None)],
            u'video': [Column(name=u'id', fb_type='string', sqlite_type='TEXT', indexable=None),
                       Column(name=u'from', fb_type='object', sqlite_type='', indexable=None),
                       Column(name=u'tags', fb_type='array', sqlite_type='', indexable=None),
                       Column(name=u'name', fb_type='string', sqlite_type='TEXT', indexable=None),
                       Column(name=u'description', fb_type='string', sqlite_type='TEXT', indexable=None),
                       Column(name=u'picture', fb_type='string', sqlite_type='TEXT', indexable=None),
                       Column(name=u'embed_html', fb_type='string', sqlite_type='TEXT', indexable=None),
                       Column(name=u'icon', fb_type='string', sqlite_type='TEXT', indexable=None),
                       Column(name=u'source', fb_type='string', sqlite_type='TEXT', indexable=None),
                       Column(name=u'created_time', fb_type='string', sqlite_type='TEXT', indexable=None),
                       Column(name=u'updated_time', fb_type='string', sqlite_type='TEXT', indexable=None),
                       Column(name=u'comments', fb_type='array', sqlite_type='', indexable=None)]}}
